version: 0.1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-alpha"

configuration:
  - Debug
  - Release

nuget:
  account_feed: true
  project_feed: true

install:
  - cinst stylecop

build:
  publish_nuget: true
