version: 0.1.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

nuget:
  account_feed: true
  project_feed: true

install:
  - cinst stylecop

build:
  publish_nuget: true
